### ISSUE TITLE
capital letters in path to socket directory cause crash

### ISSUE THREAD

**Issue by kanishka-azimi** [obsidiansystems/gargoyle#9]
gargoyle-psql databrary-nix-db
+ cat ./schema/00.sql ....
gargoyle-postgres-monitor: user error (startLocalPostgres: Unexpected output from postgres: "WARNING: could not create Unix-domain socket in directory \"/tmp/nix-build-databrary-1.drv-0/databrary-stage-minyong-DBD-826-metadata3/databrary-nix-db/work\"")
---------
First failure after running this for a long time, I believe its a problem with "DBD" in the path having capital letters.

**Comment by ali-abrar** [comment]
Is this happening on a case insensitive file system?

**Comment by kanishka-azimi** [comment]
I think its case sensitive, vanilla centos...not that familiar. 
```
[ka988@devdatabrary2 ~]$ mount | column -t
tmpfs                    on  /tmp                             type  tmpfs        (rw,nosuid,nodev,relatime,seclabel,size=2097152k)
...
/dev/mapper/centos-home  on  /home                            type  ext4         (rw,relatime,seclabel,data=ordered)
/dev/mapper/centos-nix   on  /nix                             type  ext4         (rw,relatime,seclabel)
```
Just providing for you all, I have a workaround myself.

**Comment by kanishka-azimi** [comment]
This is consistently reproducible on Centos. It doesn't affect me much, so I will close. Feel free to reopen or contact me about reproducing.

Generally, we are considering going more lightweight, swapping in a shell script or makefile to perform what this library does for us.
